apiVersion: v1
kind: Service
metadata:
  name: library-api
  labels:
    app: library-api
spec:
  type: ClusterIP
  selector:
    app: library-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
