[package]
name = "library-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "library-server"
path = "src/server.rs"

[[bin]]
name = "library-client"
path = "src/client.rs"

[dependencies]
proto-gen = { path = "../../crates/proto-gen" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }
axum = { version = "0.8.9" }
connectrpc = { version = "0.8.1", features = ["axum", "client"] }
async-trait = "0.1.91"
http = '1.5.0'
sea-orm = { version = "2.0.1", features = [
  "sqlx-postgres",
  "runtime-tokio",
  "macros",
] }
serde = "1.0.229"
config = "0.15"
